server:
  port: 2333
  address: 0.0.0.0
lavalink:
  server:
    password: "you_password"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    bufferDurationMs: 400 
    frameBufferDurationMs: 5000 
    opusEncodingQuality: 10
    resamplingQuality: LOW 
    trackStuckThresholdMs: 10000 
    useSeekGhosting: true 
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true
    #ratelimit:
      #ipBlocks: ["1.0.0.0/8", "..."]
      #excludedIps: ["...", "..."]
      #strategy: "RotateOnBan"
      #searchTriggersFail: true
      #retryLimit: -1
    #youtubeConfig:
      #email: ""
      #password: ""
    #httpConfig:
      #proxyHost: "localhost"
      #proxyPort: 3128
      #proxyUser: ""
      #proxyPassword: ""

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""

logging:
  file:
    path: ./logs/

  level:
    root: INFO
    lavalink: INFO

  logback:
    rollingpolicy:
      max-file-size: 1GB
      max-history: 30
      